import { Ref } from "../../factory/Ref";
export default class CSSStyle {
    private _style;
    constructor(style: CSSStyleDeclaration);
    get alignContent(): string;
    set alignContent(value: string | Ref<any>);
    get alignItems(): string;
    set alignItems(value: string | Ref<any>);
    get alignSelf(): string;
    set alignSelf(value: string | Ref<any>);
    get alignmentBaseline(): string;
    set alignmentBaseline(value: string | Ref<any>);
    get all(): string;
    set all(value: string | Ref<any>);
    get animation(): string;
    set animation(value: string | Ref<any>);
    get animationDelay(): string;
    set animationDelay(value: string | Ref<any>);
    get animationDirection(): string;
    set animationDirection(value: string | Ref<any>);
    get animationDuration(): string;
    set animationDuration(value: string | Ref<any>);
    get animationFillMode(): string;
    set animationFillMode(value: string | Ref<any>);
    get animationIterationCount(): string;
    set animationIterationCount(value: string | Ref<any>);
    get animationName(): string;
    set animationName(value: string | Ref<any>);
    get animationPlayState(): string;
    set animationPlayState(value: string | Ref<any>);
    get animationTimingFunction(): string;
    set animationTimingFunction(value: string | Ref<any>);
    get backfaceVisibility(): string;
    set backfaceVisibility(value: string | Ref<any>);
    get background(): string;
    set background(value: string | Ref<any>);
    get backgroundAttachment(): string;
    set backgroundAttachment(value: string | Ref<any>);
    get backgroundBlendMode(): string;
    set backgroundBlendMode(value: string | Ref<any>);
    get backgroundClip(): string;
    set backgroundClip(value: string | Ref<any>);
    get backgroundColor(): string;
    set backgroundColor(value: string | Ref<any>);
    get backgroundImage(): string;
    set backgroundImage(value: string | Ref<any>);
    get backgroundOrigin(): string;
    set backgroundOrigin(value: string | Ref<any>);
    get backgroundPosition(): string;
    set backgroundPosition(value: string | Ref<any>);
    get backgroundPositionX(): string;
    set backgroundPositionX(value: string | Ref<any>);
    get backgroundPositionY(): string;
    set backgroundPositionY(value: string | Ref<any>);
    get backgroundRepeat(): string;
    set backgroundRepeat(value: string | Ref<any>);
    get backgroundSize(): string;
    set backgroundSize(value: string | Ref<any>);
    get border(): string;
    set border(value: string | Ref<any>);
    get borderBottom(): string;
    set borderBottom(value: string | Ref<any>);
    get borderBottomColor(): string;
    set borderBottomColor(value: string | Ref<any>);
    get borderBottomLeftRadius(): string;
    set borderBottomLeftRadius(value: string | Ref<any>);
    get borderBottomRightRadius(): string;
    set borderBottomRightRadius(value: string | Ref<any>);
    get borderBottomStyle(): string;
    set borderBottomStyle(value: string | Ref<any>);
    get borderBottomWidth(): string;
    set borderBottomWidth(value: string | Ref<any>);
    get borderCollapse(): string;
    set borderCollapse(value: string | Ref<any>);
    get borderColor(): string;
    set borderColor(value: string | Ref<any>);
    get borderImage(): string;
    set borderImage(value: string | Ref<any>);
    get borderImageOutset(): string;
    set borderImageOutset(value: string | Ref<any>);
    get borderImageRepeat(): string;
    set borderImageRepeat(value: string | Ref<any>);
    get borderImageSlice(): string;
    set borderImageSlice(value: string | Ref<any>);
    get borderImageSource(): string;
    set borderImageSource(value: string | Ref<any>);
    get borderImageWidth(): string;
    set borderImageWidth(value: string | Ref<any>);
    get borderLeft(): string;
    set borderLeft(value: string | Ref<any>);
    get borderLeftColor(): string;
    set borderLeftColor(value: string | Ref<any>);
    get borderLeftStyle(): string;
    set borderLeftStyle(value: string | Ref<any>);
    get borderLeftWidth(): string;
    set borderLeftWidth(value: string | Ref<any>);
    get borderRadius(): string;
    set borderRadius(value: string | Ref<any>);
    get borderRight(): string;
    set borderRight(value: string | Ref<any>);
    get borderRightColor(): string;
    set borderRightColor(value: string | Ref<any>);
    get borderRightStyle(): string;
    set borderRightStyle(value: string | Ref<any>);
    get borderRightWidth(): string;
    set borderRightWidth(value: string | Ref<any>);
    get borderSpacing(): string;
    set borderSpacing(value: string | Ref<any>);
    get borderStyle(): string;
    set borderStyle(value: string | Ref<any>);
    get borderTop(): string;
    set borderTop(value: string | Ref<any>);
    get borderTopColor(): string;
    set borderTopColor(value: string | Ref<any>);
    get borderTopLeftRadius(): string;
    set borderTopLeftRadius(value: string | Ref<any>);
    get borderTopRightRadius(): string;
    set borderTopRightRadius(value: string | Ref<any>);
    get borderTopStyle(): string;
    set borderTopStyle(value: string | Ref<any>);
    get borderTopWidth(): string;
    set borderTopWidth(value: string | Ref<any>);
    get borderWidth(): string;
    set borderWidth(value: string | Ref<any>);
    get boxShadow(): string;
    set boxShadow(value: string | Ref<any>);
    get boxSizing(): string;
    set boxSizing(value: string | Ref<any>);
    get breakAfter(): string;
    set breakAfter(value: string | Ref<any>);
    get breakBefore(): string;
    set breakBefore(value: string | Ref<any>);
    get breakInside(): string;
    set breakInside(value: string | Ref<any>);
    get captionSide(): string;
    set captionSide(value: string | Ref<any>);
    get clear(): string;
    set clear(value: string | Ref<any>);
    get clip(): string;
    set clip(value: string | Ref<any>);
    get color(): string;
    set color(value: string | Ref<any>);
    get columnCount(): string;
    set columnCount(value: string | Ref<any>);
    get columnFill(): string;
    set columnFill(value: string | Ref<any>);
    get columnGap(): string;
    set columnGap(value: string | Ref<any>);
    get columnRule(): string;
    set columnRule(value: string | Ref<any>);
    get columnRuleColor(): string;
    set columnRuleColor(value: string | Ref<any>);
    get columnRuleStyle(): string;
    set columnRuleStyle(value: string | Ref<any>);
    get columnRuleWidth(): string;
    set columnRuleWidth(value: string | Ref<any>);
    get columnSpan(): string;
    set columnSpan(value: string | Ref<any>);
    get columnWidth(): string;
    set columnWidth(value: string | Ref<any>);
    get columns(): string;
    set columns(value: string | Ref<any>);
    get content(): string;
    set content(value: string | Ref<any>);
    get counterIncrement(): string;
    set counterIncrement(value: string | Ref<any>);
    get counterReset(): string;
    set counterReset(value: string | Ref<any>);
    get cursor(): string;
    set cursor(value: string | Ref<any>);
    get direction(): string;
    set direction(value: string | Ref<any>);
    get display(): string;
    set display(value: string | Ref<any>);
    get emptyCells(): string;
    set emptyCells(value: string | Ref<any>);
    get filter(): string;
    set filter(value: string | Ref<any>);
    get flex(): string;
    set flex(value: string | Ref<any>);
    get flexBasis(): string;
    set flexBasis(value: string | Ref<any>);
    get flexDirection(): string;
    set flexDirection(value: string | Ref<any>);
    get flexFlow(): string;
    set flexFlow(value: string | Ref<any>);
    get flexGrow(): string;
    set flexGrow(value: string | Ref<any>);
    get flexShrink(): string;
    set flexShrink(value: string | Ref<any>);
    get flexWrap(): string;
    set flexWrap(value: string | Ref<any>);
    get float(): string;
    set float(value: string | Ref<any>);
    get font(): string;
    set font(value: string | Ref<any>);
    get fontFamily(): string;
    set fontFamily(value: string | Ref<any>);
    get fontFeatureSettings(): string;
    set fontFeatureSettings(value: string | Ref<any>);
    get fontKerning(): string;
    set fontKerning(value: string | Ref<any>);
    get fontStretch(): string;
    set fontStretch(value: string | Ref<any>);
    get fontStyle(): string;
    set fontStyle(value: string | Ref<any>);
    get fontVariant(): string;
    set fontVariant(value: string | Ref<any>);
    get fontVariantCaps(): string;
    set fontVariantCaps(value: string | Ref<any>);
    get fontVariantEastAsian(): string;
    set fontVariantEastAsian(value: string | Ref<any>);
    get fontVariantLigatures(): string;
    set fontVariantLigatures(value: string | Ref<any>);
    get fontVariantNumeric(): string;
    set fontVariantNumeric(value: string | Ref<any>);
    get fontVariantPosition(): string;
    set fontVariantPosition(value: string | Ref<any>);
    get fontWeight(): string;
    set fontWeight(value: string | Ref<any>);
    get gap(): string;
    set gap(value: string | Ref<any>);
    get grid(): string;
    set grid(value: string | Ref<any>);
    get gridArea(): string;
    set gridArea(value: string | Ref<any>);
    get gridAutoColumns(): string;
    set gridAutoColumns(value: string | Ref<any>);
    get gridAutoFlow(): string;
    set gridAutoFlow(value: string | Ref<any>);
    get gridAutoRows(): string;
    set gridAutoRows(value: string | Ref<any>);
    get gridColumn(): string;
    set gridColumn(value: string | Ref<any>);
    get gridColumnEnd(): string;
    set gridColumnEnd(value: string | Ref<any>);
    get gridColumnGap(): string;
    set gridColumnGap(value: string | Ref<any>);
    get gridColumnStart(): string;
    set gridColumnStart(value: string | Ref<any>);
    get gridGap(): string;
    get top(): string;
    set top(value: string | Ref<any>);
    get right(): string;
    set right(value: string | Ref<any>);
    get bottom(): string;
    set bottom(value: string | Ref<any>);
    get left(): string;
    set left(value: string | Ref<any>);
    get gridRow(): string;
    set gridRow(value: string | Ref<any>);
    get gridRowEnd(): string;
    set gridRowEnd(value: string | Ref<any>);
    get gridRowGap(): string;
    set gridRowGap(value: string | Ref<any>);
    get gridRowStart(): string;
    set gridRowStart(value: string | Ref<any>);
    get gridTemplate(): string;
    set gridTemplate(value: string | Ref<any>);
    get gridTemplateAreas(): string;
    get width(): string;
    set width(value: string | Ref<any>);
    get height(): string;
    set height(value: string | Ref<any>);
    get minWidth(): string;
    set minWidth(value: string | Ref<any>);
    get minHeight(): string;
    set minHeight(value: string | Ref<any>);
    get maxWidth(): string;
    set maxWidth(value: string | Ref<any>);
    get maxHeight(): string;
    set maxHeight(value: string | Ref<any>);
    get margin(): string;
    set margin(value: string | Ref<any>);
    get marginTop(): string;
    set marginTop(value: string | Ref<any>);
    get marginRight(): string;
    set marginRight(value: string | Ref<any>);
    get marginBottom(): string;
    set marginBottom(value: string | Ref<any>);
    get marginLeft(): string;
    set marginLeft(value: string | Ref<any>);
    get padding(): string;
    set padding(value: string | Ref<any>);
    get paddingTop(): string;
    set paddingTop(value: string | Ref<any>);
    get paddingRight(): string;
    set paddingRight(value: string | Ref<any>);
    get paddingBottom(): string;
    set paddingBottom(value: string | Ref<any>);
    get paddingLeft(): string;
    set paddingLeft(value: string | Ref<any>);
    get position(): string;
    set position(value: string | Ref<any>);
}
